server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      ###路由规则
      routes:
        - id: user-center   # 路由唯一标识
          uri: lb://user-center # 路由服务地址
          predicates:
            - Path=/user-center/**
            - Cookie=girl, zhouhuimin
            - Host=**.baidu.com,localhost
            - After=2021-08-13T16:47:24.868+08:00[Asia/Shanghai]
          filters:
            - RewritePath=/user-center/?(?<segment>.*), /$\{segment}
        - id: user-center-2   # 路由唯一标识
          uri: lb://user-center-2 # 路由服务地址
          predicates:
            - Path=/user-center-2/**
            - After=2021-08-13T16:14:24.868+08:00[Asia/Shanghai]
          filters:
            - RewritePath=/user-center-2/?(?<segment>.*), /$\{segment}
#      discovery:
#        locator:
#          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由   开启后路由规则不生效
#          lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug